version: "3"
services:
    nginx:
        build:
            context: devops/nginx/
        container_name: cartola-app-nginx
        ports:
            - "8000:80"
        volumes:
            - .:/app
            - ./devops/nginx:/etc/nginx/conf.d/
        networks:
            - cartola-app-network

    php:
        build:
            context: devops/php/
        container_name: cartola-app-php
        ports:
            - "9300:9000"
        volumes:
            - .:/app
            - ./devops/php/php-development.ini:/usr/local/etc/php/conf.d/additional.ini
        networks:
            - cartola-app-network

    db:
        image: postgres:11.5-alpine
        restart: always
        ports:
            - 5433:5432
        container_name: cartola-app-postgres
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}      
            POSTGRES_PASSWORD: ${DB_PASSWORD}   
        networks:
            - cartola-app-network

networks:
    cartola-app-network:
        driver: bridge